### ISSUE TITLE
Smart Array CPU information

### ISSUE THREAD

**Issue by litespeeddi2** [lairsdragon/check_hp#1]
How do you activate the CPU information please? 

Brilliant script by the way, so useful!

"Quick progress these days... as of Andrew Gray's inquiry I added support for
retrieving Smart Array CPU information. This is not active by default and may
be used to check and/or gather performance data."

**Comment by lairsdragon** [comment]
You should use the --perfdata Parameter:

`check_hp -H server.example.com --perfdata`

That will return the perfdata of the Array Controller

The Kudos have to go to gunny from http://www.crowdedplace.com/category/check_hp/

This Repo is only a Mirror for easy usage with my git workflows..
